name: HelloProject
version: 0.1
author: ochacker
description: Hello, World!
main: ochacker.HelloProject.HelloProject

commands:
  hello:
    description: Hello!
  kickban:
    description: Ban a player